<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

namespace Klevu\Pipelines\Exception\Pipeline;

use Klevu\Pipelines\Exception\PipelineException;
use Klevu\Pipelines\Pipeline\PipelineInterface;

class StageException extends PipelineException
{
    /**
     * @var PipelineInterface
     */
    private readonly PipelineInterface $pipeline;

    /**
     * @param PipelineInterface $pipeline
     * @param string $message
     * @param int $code
     * @param \Throwable|null $previous
     */
    public function __construct(
        PipelineInterface $pipeline,
        string $message = "",
        int $code = 0,
        ?\Throwable $previous = null,
    ) {
        $this->pipeline = $pipeline;

        parent::__construct(
            pipelineName: $pipeline::class,
            message: $message,
            code: $code,
            previous: $previous,
        );
    }

    /**
     * @return PipelineInterface
     */
    public function getPipeline(): PipelineInterface
    {
        return $this->pipeline; // TODO: Change the autogenerated stub
    }
}
